name: Generate Articles

on:
  push:
    paths:
      - 'posts/**'  # 当 posts 文件夹有变化时触发

jobs:
  generate:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      
      - name: Install dependencies
        run: npm install @xmldom/xmldom
      
      - name: Generate articles.json
        run: |
          node <<EOF
          const fs = require('fs');
          const path = require('path');
          const { DOMParser } = require('@xmldom/xmldom');
          
          // 定义 posts 文件夹路径
          const postsDir = path.join(__dirname, 'posts');
          
          // 读取 posts 文件夹中的所有文件
          fs.readdir(postsDir, (err, files) => {
            if (err) {
              console.error('读取文件夹时出错:', err);
              return;
            }
            
            const articles = files
              .filter(file => path.extname(file) === '.html')
              .map(file => {
                try {
                  // 读取文章文件内容
                  const filePath = path.join(postsDir, file);
                  const content = fs.readFileSync(filePath, 'utf8');
                  
                  // 解析 HTML 并提取元数据
                  const doc = new DOMParser().parseFromString(content, 'text/html');
                  const date = doc.querySelector('meta[name="date"]')?.getAttribute('content');
                  const title = doc.querySelector('meta[name="title"]')?.getAttribute('content');
                  
                  return {
                    date,
                    title,
                    url: `./posts/${file}`
                  };
                } catch (error) {
                  console.error(`解析 ${file} 时出错:`, error);
                  return null;
                }
              })
              .filter(article => article && article.date && article.title)
              .sort((a, b) => new Date(b.date) - new Date(a.date));
            
            // 写入 articles.json 文件
            fs.writeFileSync('articles.json', JSON.stringify(articles, null, 2));
            console.log('✅ 文章列表已更新');
          });
          EOF
      
      - name: Commit and push changes
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add articles.json
          # 仅当文件有变化时才提交
          if git diff --quiet articles.json; then
            echo "文章列表无变化，跳过提交"
          else
            git commit -m '自动更新文章列表'
            git push
          fi